/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * nlmpc_config__costFcnJacobian.c
 *
 * Code generation for function 'nlmpc_config__costFcnJacobian'
 *
 */

/* Include files */
#include "nlmpc_config__costFcnJacobian.h"
#include "nlmpc_config__costFcnJacobianAD.h"
#include "nlmpcmoveCodeGeneration_data.h"
#include "rt_nonfinite.h"
#include <string.h>

/* Type Definitions */
#ifndef typedef_cell_7
#define typedef_cell_7
typedef struct {
  real_T f1;
  real_T f2[196];
  real_T f3;
  real_T f4[16];
  real_T f5;
  real_T f6[9];
} cell_7;
#endif /* typedef_cell_7 */

#ifndef typedef_b_struct_T
#define typedef_b_struct_T
typedef struct {
  cell_7 constants;
} b_struct_T;
#endif /* typedef_b_struct_T */

/* Variable Definitions */
static boolean_T b_ADdata_not_empty;

/* Function Definitions */
void c_nlmpc_config__costFcnJacobian(void)
{
  b_ADdata_not_empty = false;
}

void nlmpc_config__costFcnJacobian(const real_T x[14], const real_T u[4],
                                   const real_T dmv[4], const real_T e[3],
                                   const real_T p[323], real_T Jx[14],
                                   real_T Ju[4], real_T Jdmv[4], real_T Je[3])
{
  static b_struct_T ADdata;
  real_T J[25];
  real_T b_x[25];
  int32_T i;
  /*  This function was generated by Model Predictive Control Toolbox
   * (Version 24.1). */
  /*  2024/05/07 03:19:27 */
  if (!b_ADdata_not_empty) {
    ADdata.constants.f1 = 0.5;
    memcpy(&ADdata.constants.f2[0], &dv3[0], 196U * sizeof(real_T));
    ADdata.constants.f3 = 0.5;
    memcpy(&ADdata.constants.f4[0], &dv4[0], 16U * sizeof(real_T));
    ADdata.constants.f5 = 0.5;
    for (i = 0; i < 9; i++) {
      ADdata.constants.f6[i] = iv[i];
    }
    b_ADdata_not_empty = true;
  }
  memcpy(&b_x[0], &x[0], 14U * sizeof(real_T));
  b_x[14] = u[0];
  b_x[18] = dmv[0];
  b_x[15] = u[1];
  b_x[19] = dmv[1];
  b_x[16] = u[2];
  b_x[20] = dmv[2];
  b_x[17] = u[3];
  b_x[21] = dmv[3];
  b_x[22] = e[0];
  b_x[23] = e[1];
  b_x[24] = e[2];
  nlmpc_config__costFcnJacobianAD(
      b_x, ADdata.constants.f1, ADdata.constants.f2, ADdata.constants.f3,
      ADdata.constants.f4, ADdata.constants.f5, ADdata.constants.f6, p, J);
  memcpy(&Jx[0], &J[0], 14U * sizeof(real_T));
  Ju[0] = J[14];
  Jdmv[0] = J[18];
  Ju[1] = J[15];
  Jdmv[1] = J[19];
  Ju[2] = J[16];
  Jdmv[2] = J[20];
  Ju[3] = J[17];
  Jdmv[3] = J[21];
  Je[0] = J[22];
  Je[1] = J[23];
  Je[2] = J[24];
}

/* End of code generation (nlmpc_config__costFcnJacobian.c) */
