/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * nlmpc_config__costFcnJacobian.c
 *
 * Code generation for function 'nlmpc_config__costFcnJacobian'
 *
 */

/* Include files */
#include "nlmpc_config__costFcnJacobian.h"
#include "MtimesLeftAdjoint.h"
#include "MtimesRightAdjoint.h"
#include "nlmpcmoveCodeGeneration_data.h"
#include "rt_nonfinite.h"
#include <emmintrin.h>
#include <string.h>

/* Type Definitions */
#ifndef typedef_cell_7
#define typedef_cell_7
typedef struct {
  real_T f1;
  real_T f2[4];
  real_T f3;
  real_T f4[16];
  real_T f5;
  real_T f6[16];
  real_T f7;
  real_T f8[4];
} cell_7;
#endif /* typedef_cell_7 */

#ifndef typedef_b_struct_T
#define typedef_b_struct_T
typedef struct {
  cell_7 constants;
} b_struct_T;
#endif /* typedef_b_struct_T */

/* Variable Definitions */
static boolean_T b_ADdata_not_empty;

/* Function Definitions */
void c_nlmpc_config__costFcnJacobian(void)
{
  b_ADdata_not_empty = false;
}

void nlmpc_config__costFcnJacobian(const real_T x[14], const real_T u[4],
                                   const real_T dmv[4], const real_T e[2],
                                   const real_T p[123], real_T Jx[14],
                                   real_T Ju[4], real_T Jdmv[4], real_T Je[2])
{
  static b_struct_T ADdata;
  __m128d r;
  __m128d r1;
  real_T arg47[24];
  real_T inputVariables[24];
  real_T arg39[14];
  real_T arg46[14];
  real_T arg30[4];
  real_T arg31[4];
  real_T arg34[4];
  real_T dmvjac[4];
  real_T arg27[2];
  real_T arg28[2];
  real_T ejac[2];
  real_T d;
  real_T d1;
  real_T d2;
  real_T d3;
  int32_T i;
  int32_T i1;
  /*  This function was generated by Model Predictive Control Toolbox
   * (Version 24.1). */
  /*  2024/08/21 18:10:05 */
  if (!b_ADdata_not_empty) {
    ADdata.constants.f1 = 0.5;
    ADdata.constants.f2[0] = 100000.0;
    ADdata.constants.f2[1] = 0.0;
    ADdata.constants.f2[2] = 0.0;
    ADdata.constants.f2[3] = 100000.0;
    ADdata.constants.f3 = 0.5;
    ADdata.constants.f5 = 0.5;
    for (i = 0; i < 16; i++) {
      ADdata.constants.f4[i] = iv3[i];
      ADdata.constants.f6[i] = dv[i];
    }
    ADdata.constants.f7 = 0.5;
    ADdata.constants.f8[0] = 1.0;
    ADdata.constants.f8[1] = 0.0;
    ADdata.constants.f8[2] = 0.0;
    ADdata.constants.f8[3] = 1.0;
    b_ADdata_not_empty = true;
  }
  memcpy(&inputVariables[0], &x[0], 14U * sizeof(real_T));
  inputVariables[14] = u[0];
  inputVariables[18] = dmv[0];
  inputVariables[15] = u[1];
  inputVariables[19] = dmv[1];
  inputVariables[16] = u[2];
  inputVariables[20] = dmv[2];
  inputVariables[17] = u[3];
  inputVariables[21] = dmv[3];
  inputVariables[22] = e[0];
  inputVariables[23] = e[1];
  memset(&arg47[0], 0, 24U * sizeof(real_T));
  d = e[0] * ADdata.constants.f7;
  d1 = e[1] * ADdata.constants.f7;
  arg28[0] = d * ADdata.constants.f8[0] + d1 * ADdata.constants.f8[1];
  arg28[1] = d * ADdata.constants.f8[2] + d1 * ADdata.constants.f8[3];
  MtimesRightAdjoint(arg28, ejac);
  MtimesRightAdjoint(&inputVariables[22], arg27);
  MtimesLeftAdjoint(ADdata.constants.f8, arg27, arg28);
  r = _mm_loadu_pd(&arg28[0]);
  r1 = _mm_loadu_pd(&ejac[0]);
  _mm_storeu_pd(
      &ejac[0],
      _mm_add_pd(r1, _mm_mul_pd(r, _mm_set1_pd(ADdata.constants.f7))));
  d = dmv[0];
  d1 = dmv[1];
  d2 = dmv[2];
  d3 = dmv[3];
  for (i = 0; i < 4; i++) {
    i1 = i << 2;
    arg34[i] = ((d * ADdata.constants.f5 * ADdata.constants.f6[i1] +
                 d1 * ADdata.constants.f5 * ADdata.constants.f6[i1 + 1]) +
                d2 * ADdata.constants.f5 * ADdata.constants.f6[i1 + 2]) +
               d3 * ADdata.constants.f5 * ADdata.constants.f6[i1 + 3];
  }
  b_MtimesRightAdjoint(arg34, dmvjac);
  b_MtimesRightAdjoint(&inputVariables[18], arg30);
  b_MtimesLeftAdjoint(ADdata.constants.f6, arg30, arg31);
  d = u[0];
  d1 = u[1];
  d2 = u[2];
  d3 = u[3];
  for (i = 0; i < 4; i++) {
    dmvjac[i] += arg31[i] * ADdata.constants.f5;
    i1 = i << 2;
    arg34[i] = ((d * ADdata.constants.f3 * ADdata.constants.f4[i1] +
                 d1 * ADdata.constants.f3 * ADdata.constants.f4[i1 + 1]) +
                d2 * ADdata.constants.f3 * ADdata.constants.f4[i1 + 2]) +
               d3 * ADdata.constants.f3 * ADdata.constants.f4[i1 + 3];
  }
  __m128d r2;
  real_T b_inputVariables[2];
  b_MtimesRightAdjoint(arg34, arg30);
  b_MtimesRightAdjoint(&inputVariables[14], arg31);
  b_MtimesLeftAdjoint(ADdata.constants.f4, arg31, arg34);
  r = _mm_loadu_pd(&arg34[0]);
  r1 = _mm_loadu_pd(&arg30[0]);
  r2 = _mm_set1_pd(ADdata.constants.f3);
  _mm_storeu_pd(&arg30[0], _mm_add_pd(r1, _mm_mul_pd(r, r2)));
  r = _mm_loadu_pd(&arg34[2]);
  r1 = _mm_loadu_pd(&arg30[2]);
  _mm_storeu_pd(&arg30[2], _mm_add_pd(r1, _mm_mul_pd(r, r2)));
  r = _mm_loadu_pd(&inputVariables[12]);
  r1 = _mm_set1_pd(ADdata.constants.f1);
  _mm_storeu_pd(&arg28[0],
                _mm_mul_pd(_mm_sub_pd(r, _mm_loadu_pd(&p[121])), r1));
  b_inputVariables[0] =
      arg28[0] * ADdata.constants.f2[0] + arg28[1] * ADdata.constants.f2[1];
  b_inputVariables[1] =
      arg28[0] * ADdata.constants.f2[2] + arg28[1] * ADdata.constants.f2[3];
  MtimesRightAdjoint(b_inputVariables, arg27);
  memset(&arg39[0], 0, 14U * sizeof(real_T));
  arg39[12] = arg27[0];
  arg39[13] = arg27[1];
  r = _mm_loadu_pd(&inputVariables[12]);
  _mm_storeu_pd(&arg28[0], _mm_sub_pd(r, _mm_loadu_pd(&p[121])));
  MtimesRightAdjoint(arg28, arg27);
  MtimesLeftAdjoint(ADdata.constants.f2, arg27, arg28);
  memset(&arg46[0], 0, 14U * sizeof(real_T));
  r = _mm_loadu_pd(&arg28[0]);
  _mm_storeu_pd(&arg46[12], _mm_mul_pd(r, r1));
  for (i = 0; i <= 12; i += 2) {
    r = _mm_loadu_pd(&arg39[i]);
    r1 = _mm_loadu_pd(&arg46[i]);
    _mm_storeu_pd(&arg47[i], _mm_add_pd(r, r1));
  }
  arg47[14] = arg30[0];
  arg47[18] = dmvjac[0];
  arg47[15] = arg30[1];
  arg47[19] = dmvjac[1];
  arg47[16] = arg30[2];
  arg47[20] = dmvjac[2];
  arg47[17] = arg30[3];
  arg47[21] = dmvjac[3];
  arg47[22] = ejac[0];
  arg47[23] = ejac[1];
  memcpy(&Jx[0], &arg47[0], 14U * sizeof(real_T));
  Ju[0] = arg30[0];
  Jdmv[0] = dmvjac[0];
  Ju[1] = arg30[1];
  Jdmv[1] = dmvjac[1];
  Ju[2] = arg30[2];
  Jdmv[2] = dmvjac[2];
  Ju[3] = arg30[3];
  Jdmv[3] = dmvjac[3];
  Je[0] = ejac[0];
  Je[1] = ejac[1];
}

/* End of code generation (nlmpc_config__costFcnJacobian.c) */
